spring.application.name=ulica-backend

# Disable ddl-auto since schema.sql handles initialization
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Database dialect for PostGIS
spring.jpa.properties.hibernate.dialect=org.hibernate.spatial.dialect.postgis.PostgisDialect
